# Generated by iptables-save v1.4.21 on Sat Oct  4 13:34:03 2014
*mangle
:PREROUTING ACCEPT [3006:1049261]
:INPUT ACCEPT [1166:239583]
:FORWARD ACCEPT [1836:808446]
:OUTPUT ACCEPT [1192:156982]
:POSTROUTING ACCEPT [3108:976462]
COMMIT
# Completed on Sat Oct  4 13:34:03 2014
# Generated by iptables-save v1.4.21 on Sat Oct  4 13:34:03 2014
*filter
:INPUT ACCEPT [292:55780]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [332:51620]
-A INPUT -i wlan1 -p udp -m udp --dport 67 -j ACCEPT
-A INPUT -i wlan1 -p tcp -m tcp --dport 67 -j ACCEPT
-A INPUT -i wlan1 -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -i wlan1 -p tcp -m tcp --dport 53 -j ACCEPT
-A FORWARD -d 10.42.0.0/24 -o wlan1 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.42.0.0/24 -i wlan1 -j ACCEPT
-A FORWARD -i wlan1 -o wlan1 -j ACCEPT
-A FORWARD -o wlan1 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i wlan1 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Sat Oct  4 13:34:03 2014
# Generated by iptables-save v1.4.21 on Sat Oct  4 13:34:03 2014
*nat
:PREROUTING ACCEPT [84:5739]
:INPUT ACCEPT [43:3287]
:OUTPUT ACCEPT [102:6537]
:POSTROUTING ACCEPT [102:6537]
-A POSTROUTING -s 10.42.0.0/24 ! -d 10.42.0.0/24 -j MASQUERADE
COMMIT
# Completed on Sat Oct  4 13:34:03 2014
