;var jQFWlanguage = {
	language: "english",
	localize: function(translation){
		if(this.language === "english"){
			return translation;
		}
		else{
			var translated = this.viewText[this.language][translation];
			if(translated){
				return translated;
			}
			else{
				return translation;
			}
		}
	},
	viewText: {

		"dansk":{
			"Events": "Begivenheder",
			"Event Tickets": "Eventbilletter",
			"Photos": "Billeder",
			"photos in": "fotos i",
			"Albums": "Albummer",
			"Likes": "Synes godt om",
			"Like": "Synes godt om",
			"Unlike": "Synes ikke godt om længere",
			"like this": "synes godt om dette",
			"You and": "Du og",
			"Comment": "Tilføj kommentar",
			"View more comments": "Vis flere kommentarer",
			"Write a comment": "Skriv en kommentar",
			"of": "af",
			"just now": "lige nu",
			"1 minute ago": "1 minut siden",
			" minutes ago": " minutter siden",
			"1 hour ago": "1 time siden",
			" hours ago": " timer siden",
			"Yesterday": "I går",
			" days ago": " dage siden",
			" weeks ago": " uger siden",
			"Sunday": "Søndag",
			"Monday": "Mandag",
			"Tuesday": "Tirsdag",
			"Wednesday": "Onsdag",
			"Thursday": "Torsdag",
			"Friday": "Fredag",
			"Saturday": "Lørdag",
			"January": "Januar",
			"February": "Februar",
			"March": "Marts",
			"April": "April",
			"May": "Maj",
			"June": "Juni",
			"July": "Juli",
			"August": "August",
			"September": "September",
			"October": "Oktober",
			"November": "November",
			"December": "December"
		},
		
		"deutsch":{
			"Events": "Veranstaltungen",
			"Event Tickets": "Veranstaltungs Tickets",
			"Photos": "Fotos",
			"photos in": "fotos im",
			"Albums": "Alben",
			"Likes":  "Gefällt mir",
			"Like":   "Gefällt mir",
			"Unlike": "Gefällt mir nicht mehr",
			"like this": "gefällt das",
			"You and": "Dir und",
			"Comment": "Kommentar",
			"View more comments": "Alle Kommentare anzeigen",
			"Write a comment": "Kommentar schreiben",
			"of": "von",
			"just now": "gerade eben",
			"1 minute ago": "vor 1 Minute",
			" minutes ago": " Minuten",
			"1 hour ago": "vor 1 Stunde",
			" hours ago": " Stunden",
			"Yesterday": "Gestern",
			" days ago": " Tagen",
			" weeks ago": " Wochen",
			"Sunday": "Sonntag",
			"Monday": "Montag",
			"Tuesday": "Dienstag",
			"Wednesday": "Mittwoch",
			"Thursday": "Donnerstag",
			"Friday": "Freitag",
			"Saturday": "Samstag",
			"January": "Januar",
			"February": "Februar",
			"March": "März",
			"April": "April",
			"May": "Mai",
			"June": "Juni",
			"July": "Juli",
			"August": "August",
			"September": "September",
			"October": "Oktober",
			"November": "November",
			"December": "Dezember"
		},
		
		"dutch":{
			"Events": "Evenementen",
			"Event Tickets": "Evenement tickets",
			"Photos": "Foto's",
			"photos in": "foto's in",
			"Albums": "Albums",
			"Likes":  "Likes",
			"Like":   "Vind ik leuk",
			"Unlike": "Vind ik niet meer leuk",
			"like this": "vinden dit leuk",
			"You and": "Jij en",
			"Comment": "Commentaar",
			"View more comments": "Toon meer commentaren",
			"Write a comment": "Schrijf een commentaar",
			"of": "van",
			"just now": "nu net",
			"1 minute ago": "1 minuut geleden",
			" minutes ago": " minuten geleden",
			"1 hour ago": "1 uur geleden",
			" hours ago": " uur geleden",
			"Yesterday": "Gisteren",
			" days ago": " dagen geleden",
			" weeks ago": " weken geleden",
			"Sunday": "Zondag",
			"Monday": "Maandag",
			"Tuesday": "Dinsdag",
			"Wednesday": "Woensdag",
			"Thursday": "Donderdag",
			"Friday": "Vrijdag",
			"Saturday": "Zaterdag",
			"January": "Januari",
			"February": "Februari",
			"March": "Maart",
			"April": "April",
			"May": "Mei",
			"June": "Juni",
			"July": "Juli",
			"August": "Augustus",
			"September": "September",
			"October": "Oktober",
			"November": "November",
			"December": "December"	
		},
		
		"espanol": {
			"Events": "Eventos",
			"Event Tickets": "Las entradas de eventos",
			"Photos": "Fotos",
			"photos in": "fotos en",
			"Albums": "Álbumes",
			"Likes":  "Me gusta",
			"Like":   "Me gusta",
			"Unlike": "A diferencia de",
			"like this": "así",
			"You and": "Usted y",
			"Comment": "Comentario",
			"View more comments": "Ver más comentarios",
			"Write a comment": "Escribir un comentario",
			"of": "de",
			"just now": "ahora",
			"1 minute ago": "hace 1 minuto",
			" minutes ago": "hace minutos",
			"1 hour ago": "hace 1 hora",
			" hours ago": " hace horas",
			"Yesterday": "Ayer",
			" days ago": " hace días",
			" weeks ago": " hace semanas",
			"Sunday": "Domengo",
			"Monday": "Lunes",
			"Tuesday": "Martes",
			"Wednesday": "Miércoles",
			"Thursday": "Jueves",
			"Friday": "Viernes",
			"Saturday": "Sábado",
			"January": "Enero",
			"February": "Febrero",
			"March": "Marzo",
			"April": "Abril",
			"May": "Mayo",
			"June": "Junio",
			"July": "Julio",
			"August": "Agosto",
			"September": "Septiembre",
			"October": "Octubre",
			"November": "Noviembre",
			"December": "Diciembre"	
		},
		
		"francais":{
			"Events": "Evénements",
			"Event Tickets": "Billets d'événements",
			"Photos": "Photos",
			"photos in": "photos de",
			"Albums": "Albums",
			"Likes":  "Appréciations",
			"Like":   "Appréciation",
			"Unlike": "Contrairement à",
			"like this": "comme ceci",
			"You and": "Vous et",
			"Comment": "Commentaire",
			"View more comments": "Voir plus de commentaires",
			"Write a comment": "Écrire un commentaire",
			"of": "du",
			"just now": "tout à l'heure",
			"1 minute ago": "il ya 1 minute",
			" minutes ago": " il ya minutes",
			"1 hour ago": "il ya 1 heure",
			" hours ago": " il ya des heures",
			"Yesterday": "hier",
			" days ago": " il ya jours",
			" weeks ago": " il ya quelques semaines",
			"Sunday": "Dimanche",
			"Monday": "Lundi",
			"Tuesday": "Mardi",
			"Wednesday": "Mercredi",
			"Thursday": "Jeudi",
			"Friday": "Vendredi",
			"Saturday": "Samedi",
			"January": "Janvier",
			"February": "Février",
			"March": "Mars",
			"April": "Avril",
			"May": "Mai",
			"June": "Juin",
			"July": "Juillet",
			"August": "Août",
			"September": "Septembre",
			"October": "Octobre",
			"November": "Novembre",
			"December": "Décembre"	
		},
		
		"italiano":{
			"Events": "Eventi",
			"Event Tickets": "Biglietti per gli spettacoli",
			"Photos": "Foto",
			"photos in": "foto in",
			"Albums": "Album",
			"Likes":  "Mi piace",
			"Like":   "Mi piace",
			"Unlike": "Mi non piace",
			"like this": "piace questo",
			"You and": "Tu e",
			"Comment": "Commento",
			"View more comments": "Visualizza più commenti",
			"Write a comment": "Scrivi un commento",
			"of": "su",
			"just now": "proprio ora",
			"1 minute ago": "1 minuto fa",
			" minutes ago": " minuti fa",
			"1 hour ago": "1 ore ha",
			" hours ago": " ore fa",
			"Yesterday": "ieri",
			" days ago": " giorni fa",
			" weeks ago": "settimane fa",
			"Sunday": "Domenica",
			"Monday": "Lunedi",
			"Tuesday": "Martedi",
			"Wednesday": "Mercoledi",
			"Thursday": "Giovedi",
			"Friday": "Venerdi",
			"Saturday": "Sabato",
			"January": "Gennaio",
			"February": "Febbraio",
			"March": "Marzo",
			"April": "Aprile",
			"May": "Maggio",
			"June": "Giugno",
			"July": "Luglio",
			"August": "Agosto",
			"September": "Settembre",
			"October": "Otobre",
			"November": "Novembre",
			"December": "Decembre"
		},
		
		"polski":{
			"Events": "Wydarzenia",
			"Event Tickets": "",
			"Photos": "Zdjęcia",
			"photos in": "zdjęć w",
			"Albums": "Albumy",
			"Likes":  "Upodobania",
			"Like":   "Lubię to!",
			"Unlike": "Nie lubię",
			"like this": "lubi to",
			"You and": "Ty i",
			"Comment": "Dodaj komentarz",
			"View more comments": "Zobacz więcej komentarzy",
				"Write a comment": "Napisz komentarz...",
			"of": "z",
			"just now": "przed chwilą",
			"1 minute ago": "minutę temu",
			" minutes ago": " minut temu",
			"1 hour ago": " około godziny temu",
			" hours ago": " godz. temu",
			"Yesterday": "Wczoraj",
			" days ago": " dni temu",
			" weeks ago": " tygodni temu",
			"Sunday": "Niedziela",
			"Monday": "Poniedziałek",
			"Tuesday": "Wtorek",
			"Wednesday": "Środa",
			"Thursday": "Czwartek",
			"Friday": "Piątek",
			"Saturday": "Sobota",
			"January": "Stycznia",
			"February": "Lutego",
			"March": "Marca",
			"April": "Kwietnia",
			"May": "Maja",
			"June": "Czerwca",
			"July": "Lipca",
			"August": "Sierpnia",
			"September": "Września",
			"October": "Października",
			"November": "Listopada",
			"December": "Grudnia"
		},
		//brazilian portugese
		ptbr:{
			"Events": "Eventos",
			"Event Tickets": "Obter Ingressos",
			"Photos": "Fotos",
			"photos in": "fotos em",
			"Albums": "Álbuns",
			"Likes":  "Curtidas",
			"Like":   "Curtir",
			"Unlike": "Curtir (desfazer)",
			"like this": "curtiram",
			"You and": "Você e",
			"Comment": "Comentar",
			"View more comments": "Ver mais comentários",
			"Write a comment": "Escrever um comentário",
			"of": "de",
			"just now": "agora mesmo",
			"1 minute ago": "1 minuto atrás",
			" minutes ago": " minutos atrás",
			"1 hour ago": "1 hora atrás",
			" hours ago": " horas atrás",
			"Yesterday": "Ontem",
			" days ago": " dias atrás",
			" weeks ago": " semanas atrás",
			"Sunday": "Domingo",
			"Monday": "Segunda-feira",
			"Tuesday": "Terça-feira",
			"Wednesday": "Quarta-feira",
			"Thursday": "Quinta-feira",
			"Friday": "Sexta-feira",
			"Saturday": "Sabádo",
			"January": "Janeiro",
			"February": "Fevereiro",
			"March": "Março",
			"April": "Abril",
			"May": "Maio",
			"June": "Junho",
			"July": "Julho",
			"August": "Agosto",
			"September": "Setembro",
			"October": "Outubro",
			"November": "Novembro",
			"December": "Dezembro"	
		},
		
		"svenska":{
			"Events": "Händelser",
			"Event Tickets": "Evenemangsbiljetter",
			"Photos": "Bilder",
			"photos in": "foton i",
			"Albums": "Album",
			"Likes":  "Gillar",
			"Like":   "Gilla",
			"Unlike": "Till skillnad från",
			"like this": "så här",
			"You and": "Du och",
			"Comment": "Kommentar",
			"View more comments": "Visa fler kommentarer",
			"Write a comment": "Skriv en kommentar",
			"of": "av",
			"just now": "just nu",
			"1 minute ago": "1 minut sedan",
			" minutes ago": " minuter sedan",
			"1 hour ago": "1 timme sedan",
			" hours ago": " timmar sedan",
			"Yesterday": "Igår",
			" days ago": " dagar sedan",
			" weeks ago": " veckor sedan",
			"Sunday": "Sunday",
			"Monday": "Måndag",
			"Tuesday": "Tisdag",
			"Wednesday": "Onsdag",
			"Thursday": "Torsdag",
			"Friday": "Fredag",
			"Saturday": "Lördag",
			"January": "Januari",
			"February": "Februari",
			"March": "Marschera",
			"April": "April",
			"May": "Maj",
			"June": "Juni",
			"July": "Juli",
			"August": "August",
			"September": "September",
			"October": "Oktober",
			"November": "November",
			"December": "December"	
		},
		
		"turk":{
			"Events":"Etkinlikler",
			"Event Tickets":"Etkinlik Davetleri",
			"Photos":"Fotoğraflar",
			"Albums":"Albümler",
			"photos in": "Fotoğraflar iç taraf",
			"Likes":"Beğeniler",
			"Like":"Beğen",
			"Unlike":"Beğenme",
			"like this":"bunu beğen",
			"You and":"Sen ve",
			"Comment":"Yorum",
			"View more comments":"Daha fazla yorum",
			"Write a comment":"Yorum yaz",
			"of":"",
			"just now":"şimdi",
			"1 minute ago":"1 dakika önce",
			" minutes ago":" dakika önce",
			"1 hour ago":"1 saat önce",
			" hours ago":" saat önce",
			"Yesterday":"Dün",
			" days ago":" gün önce",
			" weeks ago":" hafta önce",
			"Sunday":"Pazar",
			"Monday":"Pazartesi",
			"Tuesday":"Salı",
			"Wednesday":"Çarşamba",
			"Thursday":"Perşembe",
			"Friday":"Cuma",
			"Saturday":"Cumartesi",
			"January":"Ocak",
			"February":"Şubat",
			"March":"Mart",
			"April":"Nisan",
			"May":"Mayıs",
			"June":"Haziran",
			"July":"Temmuz",
			"August":"Ağustos",
			"September":"Eylül",
			"October":"Ekim",
			"November":"Kasım",
			"December":"Aralık"
		},
		
		/*
		,newLanguageTemplate:{
			"Events": "",
			"Event Tickets": "",
			"Photos": "",
			"photos in": "",
			"Albums": "",
			"Likes":  "",
			"Like":   "",
			"Unlike": "",
			"like this": "",
			"You and": "",
			"Comment": "",
			"View more comments": "",
			"Write a comment": "",
			"of": "",
			"just now": "",
			"1 minute ago": "",
			" minutes ago": "",
			"1 hour ago": "",
			" hours ago": "",
			"Yesterday": "",
			" days ago": "",
			" weeks ago": "",
			"Sunday": "",
			"Monday": "",
			"Tuesday": "",
			"Wednesday": "",
			"Thursday": "",
			"Friday": "",
			"Saturday": "",
			"January": "",
			"February": "",
			"March": "",
			"April": "",
			"May": "",
			"June": "",
			"July": "",
			"August": "",
			"September": "",
			"October": "",
			"November": "",
			"December": ""	
		}
		*/					
	}
};